version: '3'

services:

  mongodb:
    image: mongo
    container_name: shortly_mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - shortly_network

  node:
    build: ./server
    container_name: shortly_node
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - mongodb
    networks:
      - shortly_network
    command: yarn dev

  react:
    build: ./client
    container_name: shortly_react
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - node
    networks:
      - shortly_network
    command: yarn dev

networks:
  shortly_network:
    driver: bridge
