export const MODAL_BODY_TYPES = {
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    DEFAULT: "",
};

export const RIGHT_DRAWER_TYPES = {
    NOTIFICATION: "NOTIFICATION",
    DEFAULT: "",
};
